### ISSUE TITLE
Buffer Set keys

### ISSUE THREAD

**Issue by tynes** [bcoin-org/bledger#19]
https://github.com/bcoin-org/bledger/blob/master/lib/txstate.js#L146

Using a `Set` here results in a bug because the lookup is done by reference instead of by value. A buffer with the same value should result in the value being found in the set.  Every time that I hit this code path:

https://github.com/bcoin-org/bledger/blob/master/lib/bcoin.js#L242

It cannot find the transaction. If we want to use buffers as keys, maybe we should use the `buffer-map` module like in `bcoin`

Here is an example:

```js
> let x = new Set()
undefined
> let y = Buffer.from('hey')
undefined
> x.add(y)
Set { <Buffer 68 65 79> }
> x
Set { <Buffer 68 65 79> }
> x.has(Buffer.from('hey'))
false
> x.has(y)
true
```

**Comment by nodar-chkuaselidze** [comment]
Released version of bcoin returns `hex` string instead of buffer, so in order to suppor that, 
either we change the target to `bcoin#master` or do additional checks if returned key is buffer and use buffer-maps right away.

I will leave this issue here.
