### ISSUE TITLE
Feature Request: Parent Fingerprint

### ISSUE THREAD

**Issue by tynes** [bcoin-org/bledger#33]
When calling `device.getPublicKey`, it returns a `bcoin.HDPublicKey`. It would be nice to populate the `parentFingerPrint` with the appropriate value. I think this would require the client to send 2 requests if that information doesn't come back from the the ledger-btc-app.

My usecase is comparing the equality of public keys and would also be useful for strict bip44 enforced wallets

The `parentFingerPrint` is always `0` 
```
HDPublicKey {
  depth: 3,
  parentFingerPrint: 0,
  childIndex: 2147483648,
  chainCode:
   <Buffer 6b 22 c5 12 3b a1 0a de af 4b fc bb 45 d1 a0 2d 82 8f 25 bf 86 46 95 7a 98 d0 62 87 c4 e2 b8 50>,
  publicKey:
   <Buffer 02 8b 42 cd 47 76 37 6c 82 79 1b 49 41 55 15 1f 56 c2 d7 b4 71 e0 c7 a5 26 a7 ce 60 dd 87 2e 38 67>,
  fingerPrint: -1 }
```

**Comment by nodar-chkuaselidze** [comment]
yep, I mentioned this in this issue as well: https://github.com/bcoin-org/bledger/issues/32
